# ╻ ╻╻┏┓╻╺┳┓┏━┓╻ ╻   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃╻┃┃┃┗┫ ┃┃┃ ┃┃╻┃   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗┻┛╹╹ ╹╺┻┛┗━┛┗┻┛   ╹┗╸┗━┛┗━╸┗━╸┗━┛

windowrule = match:class ^(nwg-look)$, float on
windowrule = match:class org.pulseaudio.pavucontrol, float on
windowrule = match:class ^(nm-applet)$, float on
windowrule = match:class ^(nm-connection-editor)$, float on
windowrule = match:class ^(com.obsproject.Studio)$, float on

# windowrule = float,class:^(nwg-look)$
# windowrule = float,class:org.pulseaudio.pavucontrol
# windowrule = float,class:^(nm-applet)$
# windowrule = float,class:^(nm-connection-editor)$
# windowrule = float,class:^(com.obsproject.Studio)$,title:^(Controls)$

# ╻ ╻┏━┓┏━┓╻┏ ┏━┓┏━┓┏━┓┏━╸┏━╸   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃╻┃┃ ┃┣┳┛┣┻┓┗━┓┣━┛┣━┫┃  ┣╸    ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗┻┛┗━┛╹┗╸╹ ╹┗━┛╹  ╹ ╹┗━╸┗━╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

workspace = special,gapsin:24,gapsout:64
workspace = 9, monitor:TabletDisplay

# ╻  ┏━┓╻ ╻┏━╸┏━┓   ┏━┓╻ ╻╻  ┏━╸┏━┓
# ┃  ┣━┫┗┳┛┣╸ ┣┳┛   ┣┳┛┃ ┃┃  ┣╸ ┗━┓
# ┗━╸╹ ╹ ╹ ┗━╸╹┗╸   ╹┗╸┗━┛┗━╸┗━╸┗━┛

layerrule = match:namespace notifications, no_anim on
layerrule = match:namespace bar, no_anim on
layerrule = match:namespace sidebar, no_anim on
layerrule = match:namespace menu, no_anim on
